project:
  type: website

website:
  site-url: https://anthonyromero.netlify.app/
  favicon: images/logo-final2.png
  page-navigation: true
  navbar:
    title: false
    logo: images/icon.png
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: blog.qmd
      - text: Tutoriales
        href: tutoriales.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        menu:
         - text: Source code
           href: https://github.com/ganthonyr/myblog
         - text: Report a bug
           href: https://github.com/ganthonyr/myblog/issues
      - icon: twitter
        href: https://twitter.com/ganthonyr94
        # text: My twitter account
  page-footer: 
    left: |
      Creado con ![](images/ricon24.png) y [Quarto](https://quarto.org).  
      Código fuente [![](images/github-icon.png)](https://github.com/ganthonyr/myblog)
    background: light
    right: |
     &copy; 2023 Anthony Romero Cerdán  
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    border: false
  reader-mode: true
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.google.com/specimen/Source+Sans+Pro" type="text/css"/>
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    css: styles.css
mainfont: Source Sans Pro
link-external-newwindow: TRUE