project:
  type: website

website:
  site-url: https://anthonyromero.netlify.app/
  favicon: images/logo-final2.png
  navbar:
    title: false
    logo: images/icon.png
    right:
      - text: Home
        href: index.qmd
      - text: Posts
        href: blog.qmd
      - text: Tutoriales
        href: tutoriales.qmd
      - text: CV
        href: cv.qmd
      - icon: github
        href: https://github.com/ganthonyr
      - icon: twitter
        href: https://twitter.com/ganthonyr94
  page-footer: 
    left: |
      Creado con ![](images/ricon24.png) y [Quarto](https://quarto.org).  
      Código fuente [![](images/github-icon.png)](https://github.com/ganthonyr/myblog)
    background: light
    right: |
     &copy; 2023 Anthony Romero Cerdán  
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    border: false
  reader-mode: true
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    css: styles.css