project:
  type: website

website:
  site-url: https://anthonyromero.netlify.app/
  favicon: images/icon32.png
  # google-analytics: 
  #   tracking-id: "UA-242992767-1"
  #   anonymize-ip: true
  # site-url: https://rlille.fr
  # repo-url: https://github.com/RLille/rlille.fr/
  # repo-actions: [edit, issue]
  navbar:
    title: false
    logo: images/icon.png
    # logo-alt: "an acronym for AR in black text, on top of which are placed black glasses"
    right:
      - text: Home
        href: index.qmd
      - text: Posts
        href: blog.qmd
      - text: Tutoriales
        href: tutoriales.qmd
      - text: CV
        href: cv.qmd
      - icon: github
        href: https://github.com/ganthonyr
      - icon: twitter
        href: https://twitter.com/ganthonyr94
  page-footer: 
    left: |
      Creado con ![](images/ricon24.png) y [Quarto](https://quarto.org).
    center: |
      &copy; 2023 Anthony Romero Cerdán  
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    background: light
    right: |
     Ver el código fuente en [![](images/github-icon.png)](https://github.com/ganthonyr)
    border: false
  reader-mode: true
# description: "Hola!" para los posts sí sirve como intro
format:
  html:
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    css: styles.css